name: Deploy 'every.video.near' App Components to Testnet

on:
  push:
    branches: [develop]
    paths:
      - apps/video/**

jobs:
  deploy-mainnet:
    uses: nearbuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      bw-legacy: false
      deploy-env: "testnet"
      app-name: "video"
      deploy-account-address: video.allthethings.testnet
      signer-account-address: video.allthethings.testnet
      signer-public-key: ed25519:FY9r6LsjygKyTK55KeXNw8sLY29GTSYZJLt3GkvxtoV3
    secrets: 
      SIGNER_PRIVATE_KEY: ${{ secrets.EVERY_VIDEO_SIGNER_PRIVATE_KEY_TESTNET }}